section_weights:
  organization_context: 90
  leadership: 120
  planning: 100
  support: 200
  operation: 280
  performance_evaluation: 120
  improvement: 90
question_weights:
  organization_context:
    q1: 18
    q2: 18
    q3: 18
    q4: 18
    q5: 18
  leadership:
    q1: 8
    q2: 7
    q3: 7
    q4: 7
    q5: 7
    q6: 7
    q7: 7
    q8: 7
    q9: 7
    q10: 7
    q11: 7
    q12: 7
    q13: 7
    q14: 7
    q15: 7
    q16: 7
    q17: 7
  planning:
    q1: 3
    q2: 3
    q3: 3
    q4: 3
    q5: 3
    q6: 3
    q7: 3
    q8: 3
    q9: 3
    q10: 3
    q11: 3
    q12: 3
    q13: 3
    q14: 3
    q15: 3
    q16: 3
    q17: 3
    q18: 3
    q19: 3
    q20: 3
    q21: 3
    q22: 3
    q23: 3
    q24: 3
    q25: 3
    q26: 3
    q27: 3
    q28: 3
    q29: 3
    q30: 3
    q31: 3
    q32: 3
    q33: 2
    q34: 2
  support:
    q1: 7
    q2: 7
    q3: 7
    q4: 7
    q5: 7
    q6: 7
    q7: 7
    q8: 7
    q9: 7
    q10: 7
    q11: 7
    q12: 7
    q13: 7
    q14: 7
    q15: 7
    q16: 7
    q17: 7
    q18: 7
    q19: 7
    q20: 7
    q21: 7
    q22: 7
    q23: 7
    q24: 7
    q25: 7
    q26: 7
    q27: 6
    q28: 6
    q29: 6
  operation:
    q1: 3
    q2: 3
    q3: 3
    q4: 3
    q5: 3
    q6: 3
    q7: 3
    q8: 3
    q9: 3
    q10: 3
    q11: 3
    q12: 3
    q13: 3
    q14: 3
    q15: 3
    q16: 3
    q17: 3
    q18: 3
    q19: 3
    q20: 3
    q21: 3
    q22: 3
    q23: 3
    q24: 3
    q25: 3
    q26: 3
    q27: 3
    q28: 3
    q29: 3
    q30: 3
    q31: 3
    q32: 3
    q33: 3
    q34: 3
    q35: 3
    q36: 3
    q37: 3
    q38: 3
    q39: 3
    q40: 3
    q41: 3
    q42: 3
    q43: 3
    q44: 3
    q45: 3
    q46: 3
    q47: 3
    q48: 3
    q49: 3
    q50: 3
    q51: 3
    q52: 3
    q53: 3
    q54: 3
    q55: 3
    q56: 3
    q57: 3
    q58: 3
    q59: 3
    q60: 3
    q61: 3
    q62: 3
    q63: 3
    q64: 3
    q65: 3
    q66: 3
    q67: 3
    q68: 3
    q69: 3
    q70: 3
    q71: 3
    q72: 3
    q73: 3
    q74: 3
    q75: 3
    q76: 3
    q77: 3
    q78: 3
    q79: 3
    q80: 3
    q81: 2
    q82: 2
    q83: 2
    q84: 2
    q85: 2
    q86: 2
    q87: 2
    q88: 2
    q89: 2
    q90: 2
    q91: 2
    q92: 2
    q93: 2
    q94: 2
    q95: 2
    q96: 2
    q97: 2
    q98: 2
    q99: 2
    q100: 2
  performance_evaluation:
    q1: 6
    q2: 6
    q3: 6
    q4: 6
    q5: 6
    q6: 6
    q7: 6
    q8: 6
    q9: 6
    q10: 6
    q11: 5
    q12: 5
    q13: 5
    q14: 5
    q15: 5
    q16: 5
    q17: 5
    q18: 5
    q19: 5
    q20: 5
    q21: 5
    q22: 5
  improvement:
    q1: 15
    q2: 15
    q3: 15
    q4: 15
    q5: 15
    q6: 15
question_type_base_scores:
  XO:
    'yes': 100
    'no': 0
  PJ:
    0: 0
    1: 25
    2: 50
    3: 75
    4: 100
  PW: null
